---
- hosts: default
  vars:
      splunkver: 6.2.3-264376-linux-2.6-x86_64
      installapps: true
      # ssl_enabled
      # auth_enabled

  tasks:
    - name: Ensure libselinux-python installed
      yum:  name=libselinux-python state=present

    - name: Ensure aliases.sh present
      copy: src=files/aliases.sh dest=/etc/profile.d/aliases.sh
            owner=root group=root mode=0644

    - name: Ensure EPEL GPG key is present
      copy: src=files/RPM-GPG-KEY-EPEL-6
            dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
            owner=root group=root mode=0644

    - name: Ensure EPEL repo is configured
      copy: src=files/epel.repo dest=/etc/yum.repos.d/epel.repo
            owner=root group=root mode=0644

    - name: Ensure hostname set
      hostname: name={{ inventory_hostname }}
      when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

    - name: Ensure hostname is in /etc/hosts
      lineinfile:
        dest=/etc/hosts
        regexp="^{{ ansible_default_ipv4.address }}.+$"
        line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

    # pulls from EPEL
    - name: Ensure nginx is installed
      yum: name=nginx state=present

    - name: Ensure nginx config in place
      copy: dest=/etc/nginx/nginx.conf
            src=files/nginx.conf
      notify:
        - restart nginx

    - name: Ensure nginx proxies for local Splunk
      template: src=templates/splunk.conf.j2 dest=/etc/nginx/conf.d/splunk.conf
                owner=root group=root mode=0644
      notify:
        - restart nginx

    - name: Ensure Splunk package installed
      yum:  name=/vagrant/sw/splunk-{{ splunkver }}.rpm state=present

    # https://apps.splunk.com/app/466/
    - name: Install Sideview Utils
      unarchive: src=sw/sideview-utils-lgpl_135.tgz
                 dest=/opt/splunk/etc/apps
                 creates=/opt/splunk/etc/apps/sideview_utils
      when: installapps
      notify:
        - restart splunk

    #Â https://apps.splunk.com/app/748/
    - name: Install SoS
      unarchive: src=sw/sos-splunk-on-splunk_32.tgz
                 dest=/opt/splunk/etc/apps
                 creates=/opt/splunk/etc/apps/sos
      when: installapps
      notify:
        - restart splunk

    # https://apps.splunk.com/app/1603/
    - name: Install Splunk-6 dashboard examples
      unarchive: src=sw/splunk-6x-dashboard-examples_201.tgz
                 dest=/opt/splunk/etc/apps
                 creates=/opt/splunk/etc/apps/simple_xml_examples
      when: installapps
      notify:
        - restart splunk

    # https://apps.splunk.com/app/273/
    - name: Install Splunk App for UNIX and Linux
      unarchive: src=sw/splunk-app-for-unix-and-linux_501.tgz
                 dest=/opt/splunk/etc/apps
                 creates=/opt/splunk/etc/apps/splunk_app_for_nix
      when: installapps
      notify:
        - restart splunk

    - name: Ensure Splunk service is configured
      copy: src=files/splunk.init dest=/etc/init.d/splunk
            owner=root group=root mode=0755
      notify:
        - restart splunk

    - name: Start Splunk service
      service: name=splunk state=started enabled=yes

    - name: Start nginx service
      service: name=nginx state=started enabled=yes

  handlers:
    - name: restart splunk
      service: name=splunk state=restarted

    - name: restart nginx
      service: name=nginx state=restarted

# vim: set ts=2 sw=2 et ft=ansible:
